#!/usr/bin/env python3
"""Flatten gridflock.scad + customizer.scad into one file for MakerWorld (single .scad, no includes).
Usage: uv run makerworld/build.py [-o build/makerworld/GridFlock.scad]
"""

import argparse
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
HERE = ROOT / "makerworld"

INCLUDE_RE = re.compile(r"^\s*(include|use)\s*<([^>]+)>\s*;?\s*$")
SECTION_RE = re.compile(r"^\s*/\*\s*\[(.+?)\]\s*\*/\s*$")
PARAM_RE = re.compile(r"^([A-Za-z][A-Za-z0-9_]*)\s*=")
DIRECTIVE_RE = re.compile(r"^@(include\??|drop\??)\s+(.*)$")
DECL_RE = re.compile(r"^([A-Za-z][A-Za-z0-9_]*)(\s*=\s*)(.*?)(;\s*)(//.*)?$")

MW_PLATE_COUNT = 24
MW_PART_GAP = 2
MW_BED_MARGIN = 2
MW_GRID = 42  # mirrors gridfinity's BASEPLATE_DIMENSIONS, asserted in main()
MW_MIN_FILLER = 8.5  # gridfinity's cutter asserts a cell is wider than BASEPLATE_OUTER_DIAMETER (8)

HEADER = """/**
 * GridFlock - a Gridfinity baseplate generator for small printer beds.
 *
 * Generated by makerworld/build.py; do not edit. Source, issues and full documentation:
 *   https://github.com/yawkat/GridFlock
 *
 * GridFlock is dual-licensed under MIT and CC-BY 4.0, Copyright (c) Jonas Konrad.
 * Bundles Gridfinity Rebuilt (MIT, Copyright (c) Kenneth Ruszkowski and contributors),
 *   https://github.com/kennetek/gridfinity-rebuilt-openscad
 * Both license notices are reproduced above the code they cover, below.
 */

"""


def read(path):
    return path.read_text().splitlines()


DEFINITION_RE = re.compile(r"^\s*(module\s|function\s|\$?[A-Za-z_][A-Za-z0-9_]*\s*=)")


def strip_comments(line, state):
    """Blank out comments in `line`. `state` is a one-element list holding 'inside block comment'."""
    out = ""
    i = 0
    while i < len(line):
        if state[0]:
            end = line.find("*/", i)
            if end < 0:
                return out
            state[0], i = False, end + 2
        elif line.startswith("//", i):
            return out
        elif line.startswith("/*", i):
            state[0], i = True, i + 2
        else:
            out += line[i]
            i += 1
    return out


def definitions_only(lines):
    """Drop top-level geometry: `use` imports defs only, but some libraries have demo geometry at top level."""
    out, pending, statement, depth, state = [], [], [], 0, [False]
    for line in lines:
        code = strip_comments(line, state)
        if not statement and not code.strip():
            pending.append(line)
            continue
        statement.append(line)
        depth += sum(code.count(c) for c in "{([") - sum(code.count(c) for c in "})]")
        if depth > 0 or not code.rstrip().endswith((";", "}")):
            continue
        if DEFINITION_RE.match(statement[0]):
            out.extend(pending + statement)
        pending, statement = [], []
    return out + pending + statement


def flatten(path, seen, out, definitions=False):
    """Inline `include`/`use` recursively, emitting each file at most once."""
    path = path.resolve()
    if path in seen:
        return
    seen.add(path)
    body = []
    for line in read(path):
        m = INCLUDE_RE.match(line)
        if m:
            flatten(path.parent / m.group(2), seen, out, definitions=m.group(1) == "use")
        else:
            body.append(line)
    out.append(f"// ---- begin {path.relative_to(ROOT)} ----")
    out.extend(definitions_only(body) if definitions else body)
    out.append(f"// ---- end {path.relative_to(ROOT)} ----")


def split_params(lines):
    """Split gridflock.scad into (includes, params, body); a param's `//` comments above it are its customizer description."""
    end = next(i for i, l in enumerate(lines) if SECTION_RE.match(l) and SECTION_RE.match(l).group(1) == "Hidden")
    head, params, comment, order = [], {}, [], []
    for line in lines[:end]:
        if INCLUDE_RE.match(line):
            head.append(line)
            comment = []
        elif line.strip().startswith("//"):
            comment.append(line)
        elif (m := PARAM_RE.match(line)) and not line.startswith("_"):
            params[m.group(1)] = comment + [line]
            order.append(m.group(1))
            comment = []
        else:
            comment = []
    return head, params, order, lines[end:]


def drop_file_header(lines):
    """Drop the leading comment block of customizer.scad, which documents the build, not the model."""
    i = 0
    while i < len(lines) and lines[i].strip().startswith("//"):
        i += 1
    while i < len(lines) and not lines[i].strip():
        i += 1
    return lines[i:]


def label(name):
    """Title_Case a parameter name; the customizer shows the variable name as the label."""
    return "_".join(word.capitalize() for word in name.split("_"))


def declare(name, line, value):
    """Re-emit a gridflock declaration under its label, optionally with a different default."""
    m = DECL_RE.match(line)
    return f"{label(name)}{m.group(2)}{m.group(3) if value is None else value}{m.group(4)}{m.group(5) or ''}".rstrip()


def expand(spec_lines, params):
    """Expand @include/@drop directives, tracking which parameters were accounted for."""
    out, aliases, used, errors, pending = [], [], set(), [], []
    for line in spec_lines:
        m = DIRECTIVE_RE.match(line.strip())
        if not m:
            if line.strip().startswith("//"):
                pending.append(line)
            else:
                out.extend(pending)
                pending = []
                out.append(line)
            continue
        kind, rest = m.group(1), m.group(2)
        names, _, value = (v.strip() for v in rest.partition("="))
        names, value = names.split(), value or None
        if value is not None and len(names) != 1:
            errors.append(f"a default may only be overridden for a single parameter: {rest!r}")
        # A comment directly above a single-parameter @include replaces gridflock's own description.
        description = pending if pending and len(names) == 1 and kind.startswith("include") else None
        if description is None:
            out.extend(pending)
        pending = []
        optional = kind.endswith("?")
        for name in names:
            if name not in params:
                if not optional:
                    errors.append(f"unknown parameter {name!r}")
                continue
            if name in used:
                errors.append(f"parameter {name!r} listed twice")
            used.add(name)
            if kind.startswith("include"):
                out.extend(params[name][:-1] if description is None else description)
                out.append(declare(name, params[name][-1], value))
                aliases.append(f"{name} = {label(name)};")
    out.extend(pending)
    for name in params:
        if name not in used:
            errors.append(f"parameter {name!r} is neither @include'd nor @drop'ped in customizer.scad")
    return out, aliases, errors


def drop_empty_sections(lines):
    """Remove section headers that ended up with no parameters under them."""
    out, i = [], 0
    while i < len(lines):
        if SECTION_RE.match(lines[i]):
            j = i + 1
            while j < len(lines) and not SECTION_RE.match(lines[j]):
                j += 1
            body = lines[i + 1:j]
            if any(PARAM_RE.match(b) for b in body):
                out.extend(lines[i:j])
            i = j
        else:
            out.append(lines[i])
            i += 1
    return out


def multi_plate(body):
    """Turn main()'s segment loop into a reusable piece, so plates and separators can place it."""
    patches = [
        ("module main() {", "module main(mw_plate = undef) {"),
        ("    duplicates = stacked_print ? stacked_print_duplicates : 1;",
         "    duplicates = stacked_print ? stacked_print_duplicates : 1;\n"
         "    mw_placement = stacked_print ? [] : mw_pack(\n"
         "        [for (segi = segments_in_order) compute_segment_size(segi) + [connector_margin, connector_margin] * 2],\n"
         "        bed_size - [_MW_BED_MARGIN, _MW_BED_MARGIN] * 2, _MW_PART_GAP);\n"
         "    assert(is_undef(mw_plate) || stacked_print || max([for (p = mw_placement) p[0]]) < _MW_PLATE_COUNT,\n"
         '        "This plate needs more build plates than MakerWorld can show. '
         'Pick a larger printer, or a smaller plate.");\n'
         "    assert(BASEPLATE_DIMENSIONS == [_MW_GRID, _MW_GRID], \"makerworld/build.py has the wrong grid size.\");\n"
         "    function mw_flip(i) = [\n"
         "        stacked_print && (i == 0 ? stacked_print_flip_first : stacked_print_flip) == _FLIP_X,\n"
         "        stacked_print && (i == 0 ? stacked_print_flip_first : stacked_print_flip) == _FLIP_Y\n"
         "    ];\n"
         "    function mw_segi(i) = segments_in_order[floor(i / duplicates)];\n"
         "    function mw_stack_pitch() = compute_segment_position_stacked(1, mw_segi(0), mw_flip(0))[2];"),
        # The loop becomes a module rendering one piece in its own frame; callers do the placing.
        ("    for (i = [0:len(segments_in_order)*duplicates-1]) {", "    module mw_piece(i) {"),
        ("        translate(stacked_print ? compute_segment_position_stacked(i, segi, flip) : "
         "compute_segment_position_standard(segi)) flip_segment_conditional(flip) segment(trace=[",
         "        flip_segment_conditional(flip) segment(trace=["),
        ("        global_cell_count=[len(global_trace.x), len(global_trace.y)]);\n    }\n}",
         "        global_cell_count=[len(global_trace.x), len(global_trace.y)]);\n"
         "    }\n"
         "\n"
         "    for (i = [0:len(segments_in_order) * duplicates - 1])\n"
         "        if (is_undef(mw_plate) || (stacked_print ? mw_plate == 0 : mw_placement[i][0] == mw_plate))\n"
         "        translate(is_undef(mw_plate) || stacked_print\n"
         "            ? (stacked_print ? compute_segment_position_stacked(i, mw_segi(i), mw_flip(i))\n"
         "                             : compute_segment_position_standard(mw_segi(i)))\n"
         "            : mw_placement[i][1])\n"
         "        rotate([0, 0, !is_undef(mw_plate) && !stacked_print && mw_placement[i][2] ? 90 : 0])\n"
         "        mw_piece(i);\n"
         "\n"
         "    // The separator is only where the top of one piece actually meets the bottom of the next,\n"
         "    // so it never prints over a cell opening.\n"
         "    if (stacked_print && Stacked_Separator && (is_undef(mw_plate) || mw_plate == 0))\n"
         "        for (i = [0:len(segments_in_order) * duplicates - 2]) {\n"
         "            pitch = mw_stack_pitch();\n"
         "            lower_at = compute_segment_position_stacked(i, mw_segi(i), mw_flip(i));\n"
         "            upper_at = compute_segment_position_stacked(i + 1, mw_segi(i + 1), mw_flip(i + 1));\n"
         "            band_bottom = pitch * i + _profile_height;\n"
         "            band_top = pitch * (i + 1) - _extra_height;\n"
         "            color(Stacked_Separator_Color) intersection() {\n"
         "                translate([lower_at.x, lower_at.y, band_top - _profile_height]) mw_piece(i);\n"
         "                translate([upper_at.x, upper_at.y, band_bottom + _extra_height]) mw_piece(i + 1);\n"
         "            }\n"
         "        }\n"
         "}"),
    ]
    text = "\n".join(body)
    for old, new in patches:
        if text.count(old) != 1:
            raise SystemExit(f"error: gridflock.scad changed, cannot patch for multi-plate: {old[:60]!r}")
        text = text.replace(old, new)
    lines = text.split("\n")
    start = next(i for i, l in enumerate(lines) if l.startswith("if (test_pattern == 0) {"))
    end = next(i for i in range(start, len(lines)) if lines[i] == "}")
    if any(l.strip() for l in lines[end + 1:]):
        raise SystemExit("error: gridflock.scad has top-level geometry after the test_pattern dispatch")
    return lines[:start]


def plate_modules():
    """PMM renders each mw_plate_N() on its own build plate and discards the empty ones."""
    out = [f"module mw_plate_{n}() {{ main(mw_plate = {n - 1}); }}" for n in range(1, MW_PLATE_COUNT + 1)]
    # Turn the preview back to the orientation the user asked for; the plates themselves do not care.
    out += ["", "module mw_assembly_view() { rotate([0, 0, _mw_turned ? 90 : 0]) main(); }"]
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("-o", "--output", default="build/makerworld/GridFlock.scad")
    args = ap.parse_args()

    if not (ROOT / "paths" / "puzzle.scad").exists():
        print("error: paths/puzzle.scad is missing, run `just paths` first", file=sys.stderr)
        return 1

    source = read(ROOT / "gridflock.scad")
    head, params, _order, body = split_params(source)

    spec, aliases, errors = expand(drop_file_header(read(HERE / "customizer.scad")), params)
    if errors:
        for e in errors:
            print(f"error: {e}", file=sys.stderr)
        return 1
    spec = drop_empty_sections(spec)

    deps, seen = [], set()
    for line in head:
        m = INCLUDE_RE.match(line)
        flatten(ROOT / m.group(2), seen, deps, definitions=m.group(1) == "use")

    out = [HEADER.rstrip("\n"), ""]
    out += spec
    # Everything below is implementation detail hidden from the customizer.
    out += ["", "/* [Hidden] */", ""]
    # Ahead of the epilogue: a top-level assignment can only see names defined before it.
    out += [f"_MW_PLATE_COUNT = {MW_PLATE_COUNT};", f"_MW_PART_GAP = {MW_PART_GAP};",
            f"_MW_BED_MARGIN = {MW_BED_MARGIN};", f"_MW_MIN_FILLER = {MW_MIN_FILLER};", f"_MW_GRID = {MW_GRID};", ""]
    out += ["// Map the capitalized customizer labels back onto gridflock's own variable names."]
    out += aliases + [""]
    out += ["// ---- begin makerworld/epilogue.scad ----"]
    out += read(HERE / "epilogue.scad")
    out += ["// ---- end makerworld/epilogue.scad ----", ""]
    out += deps
    out += multi_plate(body)
    out += ["", "// One segment per build plate; MakerWorld drops the plates that come out empty.",
            "// mw_assembly_view is the preview of the whole plate and is not part of the exported 3MF."]
    out += plate_modules()

    dest = ROOT / args.output
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text("\n".join(out) + "\n")
    exposed = sum(1 for l in spec if PARAM_RE.match(l))
    print(f"{dest.relative_to(ROOT)}: {len(out)} lines, {exposed} exposed parameters, "
          f"{dest.stat().st_size / 1024:.0f} KiB")
    return 0


if __name__ == "__main__":
    sys.exit(main())
